### ISSUE TITLE
Parse error in functions.php

### ISSUE THREAD

**Issue by zizzfizzix** [ryelle/Foxhound#121]
I've installed all the prerequisites and when I activate the theme I get:
> Parse error: syntax error, unexpected '[' in /wp-content/themes/foxhound/functions.php on line 128

**Comment by ryelle** [comment]
I'm guessing your PHP version is below 5.4, since the error you're getting sounds like an issue with the syntax introduced then. I would recommend updating your PHP version, and I'll add a note to the theme specifying version minimums. If that's not the case, can you let me know what version of PHP you're using?

Thanks for your report!

**Comment by zizzfizzix** [comment]
@ryelle thanks a lot for your quick response.
It seems to be the case. I never thought about it since I adjusted the PHP version before installation, seems the web host tricked me and it only worked once I changed it again. No issue now, thanks!
