### ISSUE TITLE
SPA challenges

### ISSUE THREAD

**Issue by Olivia101** [ryelle/Foxhound#67]
Hi,

Does your project currently overcome any of the below challenges of building a theme as a single page application?

- Search Engine Optimisation (SEO)
- Browser history
- Analytics
- Speed of initial load

**Comment by ryelle** [comment]
**Search Engine Optimisation (SEO)**

I have to admit I haven't really tested this. Google claims to run javascript on your site, so it should correctly crawl a single page app. If you use Jetpack (or presumably Yoast, or another SEO plugin) with Foxhound, the open graph tags are added to the header of your site on the initial page load. So you can paste a URL into, for example, the facebook debugger and see the correct open graph data for the page. These do not update on page navigation, but for things like social embeds, you only need that initial page's data.

**Browser history**

This works just like a normal WordPress install thanks to react-router's [browserHistory](https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#browserhistory) functionality.

**Analytics**

I haven't added this in Foxhound, but Google Analytics has a javascript library, so someone _could_ add code to fire a GA event when the page loads, or when a user does an action. I would probably add that... maybe as a [routerMiddleware](https://github.com/ryelle/Foxhound/blob/master/js/index.jsx#L51), or as a component like DocumentMeta or [BodyClass](https://github.com/ryelle/react-body-class/)

**Speed of initial load**

The data for the current page is pre-loaded in a JSON object, which is injected into the page on the server-side (see [load-data.php](https://github.com/ryelle/Foxhound/blob/master/inc/load-data.php)). This way the page isn't relying on that initial API call before it can show data. The API is called, though, in case any data has possibly changed between server & client rendering (this is probably very unlikely, but it was easier to leave the API call in, rather than trying to create a conditional).

**Comment by Olivia101** [comment]
[This article](https://www.thewpcrowd.com/wordpress/javascript-applications-wordpress-and-seo/) discusses a pretty interesting concept of building a WP theme using regular server-side rendered WordPress pages and creating only parts of the site using AngularJS/ReactJS in order to get the full benefits of SEO.
